# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06adb9691c49f7169c2a76f46107dde1f8ad7c8480b1be7a0cef1754e58dc215beb7be6037cee0fc5c8c16d472eeb43a60250cae661ae62320dbc4e2132e3dfe

test:
  secret_key_base: 33773fd9811d27dcf5ad492ba2dc499a9034a60c01d2b2dd28266db4060ab830f4301bd272973af09d4622a40472fa5c4bb10ba71264713119d1a440468761ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
